Repository kartikvirendrar/stocksearch, pull requests merged in 2022-10, with the labels that each got.

#14 feat(ui): added navigation and background color
  img/search.png
  index.html
  style.css
Labels: hacktoberfest-accepted, bug-fix

#18 team page added
  team.html
Labels: good first issue, hacktoberfest-accepted

#20 Update README.md
  README.md
Labels: documentation, hacktoberfest-accepted

#21 new contact page
  contact.html
  team.html
Labels: enhancement, hacktoberfest-accepted

#26 Style: Implement a search icon in search box placeholder.
  index.html
  style.css
Labels: enhancement, hacktoberfest-accepted

#29 Update Contributors.md
  Contributors.md
Labels: documentation, good first issue, hacktoberfest-accepted
